spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL;
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  flyway:
    enabled: false
    baseline-on-migrate: true

  h2:
    console:
      enabled: true

#logging:
#  level:
#    org:
#      hibernate:
#        type: trace

mileage:
  url:
    append: "http://localhost:8080/mileages"
  page:
    size: 5