version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD : password
      MYSQL_DATABASE : mileage

  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.5
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERRTISE_PORT: 9092
      KAFKA_CREATE_TOPICS: "reviewed:1:1" # Topic:Partition 수:Replica 수
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
